### PR TITLE
Adds a menu to show license and about information

### PR DESCRIPTION
**Pull request by dsilhavy**
This PR adds a menu selection on the top right with the items "License" and "About". See screenshots below for more details:

## Menu
Bildschirmfoto 2023-09-05 um 13 26 01

## Menu Selection
Bildschirmfoto 2023-09-05 um 13 26 09

## License
Bildschirmfoto 2023-09-05 um 13 25 51

## About
Bildschirmfoto 2023-09-05 um 13 26 55

### CODE REVIEW

**Comment by jordijoangimenez** [comment]
You are fast, Daniel.
I'd include the attribution notice. And I'd also include the "copyrighters"/authors... I mean anything that is not visible that is in the code may find a place here.

Something like this (at the end)
Screenshot_2023-09-05-13-50-04-44

**Comment by dsilhavy** [comment]
Added more details in the about section and an auto-generated list of dependencies, see below:

## About 
Bildschirmfoto 2023-09-06 um 10 48 19

## Menu
Bildschirmfoto 2023-09-06 um 10 48 30

## Attribution Notice
Bildschirmfoto 2023-09-06 um 10 48 37

**Comment by jordijoangimenez** [comment]
Wow! 👏

**Comment by dsilhavy** [comment]
Updated "about" view. Also added scrollable view in case all the information does not fit into the window.

## Part 1
Bildschirmfoto 2023-09-08 um 10 28 47

## Part 2
Bildschirmfoto 2023-09-08 um 10 28 53

**Pull request merged**
